import 'dart:convert';

import 'package:equatable/equatable.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

/// One exercise of the bundled catalog, trimmed from the exercises dataset
/// down to what matching and the media cache need.
///
/// [gif] and [image] are paths inside the dataset repository, resolved
/// against the media base URL when downloaded. The media is © Gym visual.
class CatalogEntry extends Equatable {
  const CatalogEntry({
    required this.id,
    required this.name,
    required this.equipment,
    required this.gif,
    required this.image,
  });

  factory CatalogEntry.fromJson(Map<String, dynamic> json) => CatalogEntry(
    id: _string(json, 'id'),
    name: _string(json, 'name'),
    equipment: _string(json, 'equipment'),
    gif: _string(json, 'gif'),
    image: _string(json, 'image'),
  );

  /// The dataset's four-digit id, e.g. `"0662"`.
  final String id;

  /// Lowercase, e.g. `"dumbbell biceps curl"`.
  final String name;

  /// e.g. `"body weight"`, `"dumbbell"`.
  final String equipment;

  /// Animated demo, e.g. `"videos/0662-I4hDWkc.gif"`.
  final String gif;

  /// Still thumbnail, e.g. `"images/0662-I4hDWkc.jpg"`.
  final String image;

  static String _string(Map<String, dynamic> json, String key) {
    final value = json[key];
    if (value is String && value.isNotEmpty) return value;
    throw FormatException('Catalog entry is missing "$key"');
  }

  @override
  List<Object?> get props => [id, name, equipment, gif, image];
}

/// Every exercise the app can show a demo for.
///
/// Generated by `tool/build_exercise_catalog.dart`; never edited by hand.
class ExerciseCatalog {
  const ExerciseCatalog(this.entries);

  static const assetPath = 'assets/exercises/catalog.json';

  final List<CatalogEntry> entries;

  static Future<ExerciseCatalog> load(AssetBundle bundle) async =>
      parse(await bundle.loadString(assetPath));

  static ExerciseCatalog parse(String source) {
    final raw = jsonDecode(source);
    if (raw is! List) {
      throw const FormatException('Catalog is not a list');
    }
    return ExerciseCatalog(
      List.unmodifiable(
        raw.map((e) => CatalogEntry.fromJson(e as Map<String, dynamic>)),
      ),
    );
  }

  // ponytail: linear scan over ~1.3k entries, a map if it ever shows in a profile.
  CatalogEntry? byId(String id) {
    for (final entry in entries) {
      if (entry.id == id) return entry;
    }
    return null;
  }
}

/// Lists the exercises dataset on the "Open-source licences" page. The
/// catalog is derived from it, and its MIT licence asks for the notice to
/// travel with the copy. The same file states that the demo media is
/// © Gym visual and outside that licence.
void registerExerciseDatasetLicense() {
  LicenseRegistry.addLicense(() async* {
    yield LicenseEntryWithLineBreaks(const [
      'exercises-dataset',
    ], await rootBundle.loadString('assets/exercises/LICENSE'));
  });
}
